### ISSUE TITLE
Issue related to Database

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [chaoss/grimoirelab-sortinghat#509] opened 2021-04-05 20:41 UTC
![Screenshot 1943-01-16 at 1 40 50 AM](https://user-images.githubusercontent.com/60272417/113621330-20c62d80-9679-11eb-9f7a-fd5455abd4c5.png)

Having this error while using migrate command . 
How can i solve this ?

**Comment by vchrombie** [comment] 2021-04-06 07:52
Hi @SourabhSaraswat-191939, sorry for the inconvenience.

Can you confirm the steps you have followed to install the muggle branch of the sorting hat?
I think it is some issue with the dependency and I can help with it.

**Comment by SourabhSaraswat-191939** [comment] 2021-04-06 12:50
Hi @vchrombie ,

I installed all dependencies again and after activating venv using poetry shell ,
then I tried to run makemigrations command :

```
./manage.py makemigrations --settings=config.settings.devel
```
but it shows an error .
![Screenshot 1943-01-16 at 6 16 29 PM](https://user-images.githubusercontent.com/60272417/113712827-3af91d80-9704-11eb-89e9-781951a8898b.png)

and when i remove ".decode(errors='replace')" ,it works . I don't know it is right or wrong to do this for solving this error .
Please guide me in that .

and after that i try to run migrate command :

```
./manage.py migrate --settings=config.settings.devel
```

It show's me the same error as of the previous comment .

Please help me in solving this .

**Comment by vchrombie** [comment] 2021-04-06 16:02
Hi @SourabhSaraswat-191939, I think I need some more details on the steps how you have installed them. Do you mind having a quick chat on `#grimoirelab` at Freenode IRC?

I'm available from 21:30 to 22:30 IST. I should be available tomorrow too, let me know when it is feasible for you.

**Comment by SourabhSaraswat-191939** [comment] 2021-04-06 17:45
@vchrombie Sorry i saw this late , can you give me another time when you will be available .

**Comment by SourabhSaraswat-191939** [comment] 2021-04-07 11:07
Ok @vchrombie can we have it now .

**Comment by SourabhSaraswat-191939** [comment] 2021-04-07 11:07
> Ok @vchrombie can we have quick chat on Freenode IRC now .

**Comment by vchrombie** [comment] 2021-04-07 11:08
Yeah sure, I'm already in the channel.

**Comment by vchrombie** [comment] 2021-04-07 16:31
I hope the issue is resolved now. Can we close the issue?

**Comment by SourabhSaraswat-191939** [comment] 2021-04-07 18:07
Thank You @vchrombie , with the help of yours this issue are resolved .
Steps which are followed to solve this issue are :
1) To solve the issue : `` Error loading MySQLdb module.`` .
    we used following set of lines in config/settings/__init__.py :
```
import pymysql
pymysql.install_as_MySQLdb()
```
by using this the issue is resolved .

2) To solve database connection issue with docker Mariadb , due to which certain errors are displaying at the time of migrations commands, we setup MySQL in local system and get connected with them .

That's all we did to solve all this issues .

**Closed** 2021-04-07 18:08 UTC
