### ISSUE TITLE
UnicodeDecodeError with sortinghat

### ISSUE THREAD

**Issue by sanacl** [chaoss/grimoirelab-sortinghat#78] opened 2016-11-03 23:34 UTC
Error found using beb69772daabd168d9a7ae67d7c9f1481b73940b

How to reproduce it. Install version about and call "sortinghat"

```
bitergia@6bf66304a069:~/sortinghat$ sortinghat
Traceback (most recent call last):
  File "/usr/local/bin/sortinghat", line 4, in <module>
    __import__('pkg_resources').run_script('sortinghat==0.2.0rc1', 'sortinghat')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 59, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 813: ordinal not in range(128)
```

**Comment by aklapper** [comment] 2018-12-28 18:36
Cannot reproduce using sortinghat 0.6.9 on Python 3.7.1.

**Comment by valeriocos** [comment] 2019-01-18 15:10
Can we close this issue @sduenas , it is extremely old and it seems that cannot be reproduced?

**Comment by sduenas** [comment] 2019-01-21 15:43
Yep, let's close it.

**Closed by sduenas** 2019-01-21 15:43 UTC
Labels: bug
